# Doubleword Batch API models — model names use HuggingFace conventions
# Verify model availability at https://app.doubleword.ai/ before running
# Pricing from https://docs.doubleword.ai/batches/model-pricing
# Prices shown are "High" (1h) batch tier — "Standard" (24h) is ~30-50% cheaper
# AUTO-GENERATED by sync_doubleword_models.py — do not edit manually
# Models are NEVER removed — potentially_deprecated ones are flagged, not deleted.

DOUBLEWORD_MODELS = {

    # ═══════════════════════════════════════════════════════════
    #  TEXT-ONLY MODELS
    # ═══════════════════════════════════════════════════════════

    "dw-deepseek-v4-pro": {
        "model":      "DeepSeek/DeepSeek-V4-Pro",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "premium",
        "price_in":   0.87, "price_out": 0.87,
        "ctx":        1_024_000,
        "notes":      "FP4+FP8, Intelligence: 50",
    },
    "dw-deepseek-v4-flash": {
        "model":      "DeepSeek/DeepSeek-V4-Flash",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.07, "price_out": 0.07,
        "ctx":        1_024_000,
        "notes":      "FP4+FP8, Intelligence: 47",
    },
    "dw-kimi-k26": {
        "model":      "Moonshot/Kimi-K2.6",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "premium",
        "price_in":   0.45, "price_out": 0.45,
        "ctx":        256_000,
        "notes":      "INT4, Intelligence: 54",
    },
    "dw-glm-51": {
        "model":      "Z.ai/GLM-5.1",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "premium",
        "price_in":   0.70, "price_out": 0.70,
        "ctx":        198_000,
        "notes":      "FP8, Intelligence: 51",
    },
    "dw-gemma-4-31b-it": {
        "model":      "Google/Gemma-4-31B-IT",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.07, "price_out": 0.07,
        "ctx":        250_000,
        "notes":      "31B, Intelligence: 39",
    },
    "dw-qwen36-35b-a3b": {
        "model":      "Alibaba/Qwen3.6-35B-A3B",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.05, "price_out": 0.05,
        "ctx":        256_000,
        "notes":      "FP8, Intelligence: 43",
    },
    "dw-qwen3.5-4b": {
        "model":      "Qwen/Qwen3.5-4B",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.04, "price_out": 0.04,
        "ctx":        256_000,
        "notes":      "4B, Intelligence: 27",
    },
    "dw-nemotron-120b": {
        "model":      "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.15, "price_out": 0.15,
        "ctx":        256_000,
        "notes":      "120B MoE (12B active), NVFP4, Intelligence: 36",
    },
    "dw-olmocr-2-7b-1025-fp8": {
        "model":      "allenai/olmOCR-2-7B-1025-FP8",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.10, "price_out": 0.10,
        "ctx":        16_000,
        "notes":      "7B, FP8",
        "extra_params": {'top_k': 1},
    },
    "dw-lightonocr-2-1b-bbox-soup": {
        "model":      "lightonai/LightOnOCR-2-1B-bbox-soup",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.05, "price_out": 0.05,
        "ctx":        16_000,
        "notes":      "1B",
        "extra_params": {'top_k': 1},
    },
    "dw-qwen3.5-9b": {
        "model":      "Qwen/Qwen3.5-9B",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.03, "price_out": 0.03,
        "ctx":        256_000,
        "notes":      "9B, Intelligence: 32",
    },
    "dw-qwen3.5-9b-dotfxt": {
        "model":      "Qwen/Qwen3.5-9B-dotfxt",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.06, "price_out": 0.06,
        "ctx":        256_000,
        "notes":      "9B dotfxt, Intelligence: 32",
    },
    "dw-qwen3.5-35b": {
        "model":      "Qwen/Qwen3.5-35B-A3B-FP8",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.05, "price_out": 0.05,
        "ctx":        256_000,
        "notes":      "35B MoE (3B active), Intelligence: 37",
    },
    "dw-qwen3.5-35b-dotfxt": {
        "model":      "Qwen/Qwen3.5-35B-A3B-dotfxt",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.10, "price_out": 0.10,
        "ctx":        256_000,
        "notes":      "35B MoE (3B active) dotfxt, FP8, Intelligence: 37",
    },
    "dw-qwen3-14b": {
        "model":      "Qwen/Qwen3-14B-FP8",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.02, "price_out": 0.02,
        "ctx":        32_000,
        "notes":      "14B, FP8, Intelligence: 13",
    },
    "dw-qwen3.5-397b": {
        "model":      "Qwen/Qwen3.5-397B-A17B",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.15, "price_out": 0.15,
        "ctx":        256_000,
        "notes":      "397B MoE (17B active), FP8, Intelligence: 45",
    },
    "dw-qwen3.5-397b-dotfxt": {
        "model":      "Qwen/Qwen3.5-397B-A17B-dotfxt",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.30, "price_out": 0.30,
        "ctx":        256_000,
        "notes":      "397B MoE (17B active) dotfxt, FP8, Intelligence: 45",
    },
    "dw-gpt-oss-20b": {
        "model":      "openai/gpt-oss-20b",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.02, "price_out": 0.02,
        "ctx":        128_000,
        "notes":      "Intelligence: 25",
    },
    "dw-deepseek-ocr-2": {
        "model":      "deepseek-ai/DeepSeek-OCR-2",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.05, "price_out": 0.05,
        "ctx":        16_000,
        "notes":      "",
    },

    # ═══════════════════════════════════════════════════════════
    #  VISION-LANGUAGE MODELS
    # ═══════════════════════════════════════════════════════════

    "dw-qwen3-vl-30b": {
        "model":      "Qwen/Qwen3-VL-30B-A3B-Instruct-FP8",
        "multimodal": True,
        "modalities": ["text", "image", "video"],
        "tier":       "ultra_cheap",
        "price_in":   0.05, "price_out": 0.05,
        "ctx":        256_000,
        "notes":      "30B MoE (3B active), vision-language, FP8, Intelligence: 46",
    },
    "dw-qwen3-vl-235b": {
        "model":      "Qwen/Qwen3-VL-235B-A22B-Instruct-FP8",
        "multimodal": True,
        "modalities": ["text", "image", "video"],
        "tier":       "ultra_cheap",
        "price_in":   0.10, "price_out": 0.10,
        "ctx":        256_000,
        "notes":      "235B MoE (22B active), vision-language, FP8, Intelligence: 21",
    },

    # ═══════════════════════════════════════════════════════════
    #  EMBEDDING MODELS
    # ═══════════════════════════════════════════════════════════

    "dw-qwen3-embedding-9b": {
        "model":      "Qwen/Qwen3-Embedding-9B",
        "multimodal": False,
        "modalities": ["text"],
        "tier":       "ultra_cheap",
        "price_in":   0.02, "price_out": 0.02,
        "ctx":        32_000,
        "notes":      "9B embedding, MTEB: 70.6",
    },
}
